-- ===========================================================================
-- ARGUS — Phase 7.3: Slack multi-workspace install (D-140 .. D-146)
--
-- WHY THIS IS A SEPARATE FILE, AND WHY IT RUNS ON EVERY BOOT.
--
-- `schema_pg.sql` is a from-scratch definition: `bootstrap_schema_if_needed()`
-- applies it exactly once, when `public.tenant` does not yet exist. That was
-- correct through 7.2, when the only database in the world was created from
-- it. It stopped being sufficient the moment ARGUS went live (D-139): the
-- Render database ALREADY has the 7.2 schema, so nothing in `schema_pg.sql`
-- will ever run against it again.
--
-- So 7.3's objects live here instead, and this file is written to be
-- idempotent — every statement is IF NOT EXISTS, CREATE OR REPLACE, or
-- guarded by a catalogue lookup — and is applied on EVERY boot, against both
-- a brand-new database and the live one. One source of truth for 7.3, no
-- duplication between "fresh install" and "upgrade" paths, and no manual
-- migration step for a non-technical owner to run (D-141).
--
-- WHAT 7.3 ADDS, IN ONE PARAGRAPH.
--
-- Phase 6.5 gave ARGUS a Slack identity by having Dirgh install one app into
-- one workspace by hand and save three secrets to files on his laptop. That
-- does not survive contact with fifteen pilot teams. 7.3 replaces it with
-- Slack's OAuth v2 distribution flow: one ARGUS Slack app, installed N times
-- by N workspaces, each install producing its own bot token, each token bound
-- to exactly one ARGUS tenant, stored encrypted, and routed back to that
-- tenant by `team_id` when a button is clicked.
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- 1. Install claims learn which provider they are for.
--
-- 7.2 minted one kind of one-time token: "click here to install the ARGUS
-- GitHub App." 7.3 mints a second: "click here to add ARGUS to your Slack."
-- They are the same shape and live in the same table, which means that
-- without this column a Slack install link would be redeemable by the GitHub
-- setup redirect and vice versa — a token confusion bug, and the kind that
-- reads as harmless until someone connects the wrong account to the wrong
-- tenant. `provider` closes it, and both redeeming functions below now check
-- it (D-142).
-- ---------------------------------------------------------------------------
ALTER TABLE install_claim
    ADD COLUMN IF NOT EXISTS provider TEXT NOT NULL DEFAULT 'github';

DO $ck$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'install_claim_provider_ck') THEN
        ALTER TABLE install_claim
            ADD CONSTRAINT install_claim_provider_ck CHECK (provider IN ('github', 'slack'));
    END IF;
END
$ck$;


-- ---------------------------------------------------------------------------
-- 2. The workspace token itself.
--
-- One row per (tenant, Slack workspace). The `integration` row that already
-- exists for source='slack' remains the workspace's identity record — this
-- table holds only the credential, deliberately separated so that the
-- sensitive column lives in exactly one place with exactly one access path.
--
-- `token_ciphertext` is AES-256-GCM (see slack_crypto.py), keyed by a value
-- that exists ONLY in this host's environment and never in this database.
-- That is the 7.3 answer to a question 6.5 dodged: Phase 6 kept the bot token
-- in a file on Dirgh's laptop and stored a POINTER to it (D-087's rule,
-- `integration.credential_ref`). With fifteen workspaces there is no laptop
-- and no file — the token has to live in Postgres. Encrypting it keeps the
-- spirit of the rule intact: a stolen database dump yields ciphertext, and
-- the key is not in the dump (D-143).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS slack_workspace_token (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id               UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    integration_id          BIGINT NOT NULL,
    team_id                 TEXT NOT NULL,
    team_name               TEXT,
    -- The bot's own user id in that workspace. Needed to ignore ARGUS's own
    -- messages in the event stream, which is how a bot writes itself an
    -- infinite loop.
    bot_user_id             TEXT,
    app_id                  TEXT,
    installer_slack_user_id TEXT,
    scopes                  TEXT NOT NULL,
    token_ciphertext        TEXT NOT NULL,
    -- Lets a future key rotation re-encrypt row by row instead of all at once.
    key_version             INTEGER NOT NULL DEFAULT 1,
    installed_at            TEXT NOT NULL,
    rotated_at              TEXT,
    revoked_at              TEXT,
    revoked_reason          TEXT,
    UNIQUE (id, tenant_id),
    UNIQUE (tenant_id, integration_id),
    FOREIGN KEY (integration_id, tenant_id) REFERENCES integration(id, tenant_id)
);

-- A Slack workspace belongs to at most ONE pilot tenant at a time.
--
-- Without this, two tenants could each redeem their own install link from the
-- same workspace, and `argus_resolve_slack_team()` would return two rows for
-- one `team_id` — at which point every button click in that workspace is
-- routed by coin flip. A partial unique index (live installs only) is the
-- right shape: it still allows a workspace to leave one tenant and later join
-- another, which is a legitimate thing for a pilot to do (D-144).
--
-- Note this index is enforced across tenants, which RLS does not and cannot
-- do. That is deliberate: it is a global invariant, not tenant data.
CREATE UNIQUE INDEX IF NOT EXISTS ux_slack_team_one_live_tenant
    ON slack_workspace_token (team_id) WHERE revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS ix_slack_token_team ON slack_workspace_token (team_id);


-- ---------------------------------------------------------------------------
-- 3. The delivery ledger — idempotency for everything Slack sends us.
--
-- Slack retries any delivery it did not see a 2xx for within 3 seconds, and
-- marks the retry with `X-Slack-Retry-Num`. A retried [Handled offline] click
-- must not write a second `triage_response` row: Phase 7.8 is scored on
-- alert satisfaction, and double-counting one developer's single answer
-- corrupts the only number this whole phase exists to produce.
--
-- Events carry Slack's own `event_id`. Interactions do not carry any id at
-- all, so `dedup_key` is composed from the coordinates that identify the
-- click (see slack_app.interaction_dedup_key) rather than assumed to exist.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS slack_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    team_id         TEXT NOT NULL,
    dedup_key       TEXT NOT NULL,
    kind            TEXT NOT NULL CHECK (kind IN ('event', 'interaction')),
    event_type      TEXT,
    received_at     TEXT NOT NULL,
    outcome         TEXT NOT NULL,
    detail          TEXT,
    UNIQUE (id, tenant_id),
    UNIQUE (tenant_id, dedup_key)
);
CREATE INDEX IF NOT EXISTS ix_slackevent_team ON slack_event (tenant_id, team_id, received_at);


-- ---------------------------------------------------------------------------
-- 4. Row-level security on the two new tables.
--
-- schema_pg.sql applies RLS in a loop at migration time. That loop has
-- already run on the live database and will never run again, so these two
-- tables would arrive unprotected if this file did not do it explicitly.
-- The verification block at the bottom is what makes that a guarantee rather
-- than a promise.
-- ---------------------------------------------------------------------------
DO $rls$
DECLARE t text;
BEGIN
    FOREACH t IN ARRAY ARRAY['slack_workspace_token', 'slack_event']
    LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
        IF NOT EXISTS (SELECT 1 FROM pg_policies
                       WHERE schemaname = 'public' AND tablename = t
                         AND policyname = 'tenant_isolation') THEN
            EXECUTE format(
                'CREATE POLICY tenant_isolation ON %I
                     USING (tenant_id = argus_current_tenant())
                     WITH CHECK (tenant_id = argus_current_tenant())', t);
        END IF;
    END LOOP;
END
$rls$;


-- ---------------------------------------------------------------------------
-- 5. Grants.
--
-- roles.sql granted argus_app DML on ALL TABLES — but "ALL TABLES" in
-- Postgres means "all tables that existed when the GRANT ran", so tables
-- created by this file get nothing unless named here. A missing grant would
-- surface as a permission error at the exact moment a pilot team clicks a
-- button, which is the worst possible time to discover it.
-- ---------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON slack_workspace_token, slack_event TO argus_app;
GRANT USAGE, SELECT ON SEQUENCE slack_workspace_token_id_seq, slack_event_id_seq TO argus_app;


-- ===========================================================================
-- 6. The SECURITY DEFINER surface.
--
-- Same discipline as 7.1's API-key resolver and 7.2's installation resolver:
-- a caller that does not yet have a tenant bound (Slack's servers, or a
-- browser mid-OAuth) reaches exactly one narrow, purpose-built function
-- rather than getting a standing grant on anything.
-- ===========================================================================

-- --- 6a. Minting a claim, now provider-aware --------------------------------
-- Replaces 7.2's `argus_admin_create_install_claim`. A new name rather than a
-- new overload: adding a defaulted 5th parameter in Postgres creates a second
-- function, and every existing 4-argument call then fails as ambiguous. The
-- old one is dropped below, in the same file that switches its only caller.
CREATE OR REPLACE FUNCTION argus_admin_mint_install_claim(
        p_tenant_slug text, p_token_hash text, p_created_at text,
        p_expires_at text, p_provider text)
    RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER
    AS $fn$
    DECLARE v_tenant uuid;
    BEGIN
        SELECT id INTO v_tenant FROM tenant WHERE slug = p_tenant_slug;
        IF v_tenant IS NULL THEN
            RAISE EXCEPTION 'No such tenant: %', p_tenant_slug;
        END IF;
        INSERT INTO install_claim (tenant_id, token_hash, created_at, expires_at, provider)
        VALUES (v_tenant, p_token_hash, p_created_at, p_expires_at, p_provider);
        RETURN v_tenant;
    END;
    $fn$;
REVOKE ALL ON FUNCTION argus_admin_mint_install_claim(text, text, text, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION argus_admin_mint_install_claim(text, text, text, text, text)
    TO argus_admin;

DROP FUNCTION IF EXISTS argus_admin_create_install_claim(text, text, text, text);


-- --- 6b. Looking before we leap --------------------------------------------
-- Called TWICE, for two different reasons, and returns the tenant a live
-- claim belongs to (or NULL).
--
-- 1. /v1/slack/install calls it before redirecting anyone to Slack. Without
--    that check, someone holding a stale link authorises ARGUS inside their
--    real workspace, is bounced back, and only then told the link expired —
--    having already granted permissions for an install that then fails.
--    Checking first means nothing happens in their Slack at all.
--
-- 2. /v1/slack/oauth/callback calls it to learn the tenant BEFORE encrypting
--    the bot token, because slack_crypto binds the tenant id into the
--    ciphertext as associated data and therefore has to know it first. This
--    does NOT redeem anything: argus_claim_slack_workspace re-checks
--    `redeemed_at IS NULL` atomically a moment later, so two callbacks racing
--    on one token still end with exactly one install.
--
-- Returning the tenant id is safe: the caller already holds the claim token,
-- and there is no header, query parameter or body field anywhere in this API
-- that lets a request name the tenant it wants (see app.require_tenant). A
-- tenant id is not a credential here, by construction.
CREATE OR REPLACE FUNCTION argus_install_claim_tenant(
        p_token_hash text, p_provider text, p_at text)
    RETURNS uuid LANGUAGE sql SECURITY DEFINER STABLE
    AS $fn$
        SELECT c.tenant_id FROM install_claim c
        WHERE c.token_hash = p_token_hash
          AND c.provider = p_provider
          AND c.redeemed_at IS NULL
          AND c.expires_at > p_at
    $fn$;
REVOKE ALL ON FUNCTION argus_install_claim_tenant(text, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION argus_install_claim_tenant(text, text, text) TO argus_app;

DROP FUNCTION IF EXISTS argus_install_claim_is_live(text, text, text);


-- --- 6c. Routing an inbound Slack request to exactly one tenant -------------
-- The first move of every /v1/slack/events and /v1/slack/interactions
-- request, and the direct analogue of `argus_resolve_installation`. Revoked
-- installs are returned rather than hidden, because `app_uninstalled` can
-- legitimately arrive for a workspace we have already marked revoked and the
-- handler needs to tell "already gone" apart from "never seen".
CREATE OR REPLACE FUNCTION argus_resolve_slack_team(p_team_id text)
    RETURNS TABLE (tenant_id uuid, integration_id bigint, tenant_status text,
                   token_id bigint, revoked_at text, bot_user_id text)
    LANGUAGE sql SECURITY DEFINER STABLE
    AS $fn$
        SELECT i.tenant_id, i.id, t.status, w.id, w.revoked_at, w.bot_user_id
        FROM slack_workspace_token w
        JOIN integration i ON i.id = w.integration_id AND i.tenant_id = w.tenant_id
        JOIN tenant t      ON t.id = i.tenant_id
        WHERE w.team_id = p_team_id
          AND t.status <> 'offboarded'
        ORDER BY (w.revoked_at IS NULL) DESC, w.installed_at DESC
        LIMIT 1
    $fn$;
REVOKE ALL ON FUNCTION argus_resolve_slack_team(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION argus_resolve_slack_team(text) TO argus_app;


-- --- 6d. Redeeming a Slack install claim ------------------------------------
-- The OAuth callback's one write. Creates or refreshes the tenant's
-- `integration` row for this workspace and stores the encrypted bot token,
-- atomically, inside the caller's transaction.
--
-- OUT parameters are named out_* for the reason D-133's function records the
-- hard way: in plpgsql an OUT parameter is in scope for the whole body, so
-- naming one `tenant_id` makes every bare reference to that very common
-- column ambiguous.
--
-- `out_status` distinguishes the three outcomes the callback page must word
-- differently: 'ok', 'bad_claim' (unknown / expired / already-redeemed /
-- wrong provider), and 'team_taken' (this workspace is already live under a
-- different tenant — caught by ux_slack_team_one_live_tenant, and reported
-- WITHOUT naming the other tenant).
CREATE OR REPLACE FUNCTION argus_claim_slack_workspace(
        p_token_hash text, p_team_id text, p_team_name text, p_bot_user_id text,
        p_app_id text, p_installer text, p_scopes text, p_ciphertext text,
        p_key_version integer, p_at text)
    RETURNS TABLE (out_status text, out_tenant_id uuid, out_integration_id bigint,
                   out_token_id bigint)
    LANGUAGE plpgsql SECURITY DEFINER
    AS $fn$
    DECLARE
        v_tenant uuid; v_source bigint; v_integration bigint; v_token bigint;
        v_other uuid;
    BEGIN
        SELECT c.tenant_id INTO v_tenant FROM install_claim c
            WHERE c.token_hash = p_token_hash
              AND c.provider = 'slack'
              AND c.redeemed_at IS NULL
              AND c.expires_at > p_at;
        IF v_tenant IS NULL THEN
            RETURN QUERY SELECT 'bad_claim'::text, NULL::uuid, NULL::bigint, NULL::bigint;
            RETURN;
        END IF;

        -- Is this workspace already live under someone else? Checked before
        -- writing anything, so the common case produces a clear message
        -- rather than a raw unique-violation traceback. The index below is
        -- still the real guard against two callbacks racing each other.
        SELECT w.tenant_id INTO v_other FROM slack_workspace_token w
            WHERE w.team_id = p_team_id AND w.revoked_at IS NULL AND w.tenant_id <> v_tenant;
        IF v_other IS NOT NULL THEN
            RETURN QUERY SELECT 'team_taken'::text, NULL::uuid, NULL::bigint, NULL::bigint;
            RETURN;
        END IF;

        SELECT s.id INTO v_source FROM source s
            WHERE s.tenant_id = v_tenant AND s.name = 'slack';

        INSERT INTO integration (tenant_id, source_id, external_account_id,
                                 display_name, scope, credential_ref, installed_at)
        VALUES (v_tenant, v_source, p_team_id,
                COALESCE(NULLIF(p_team_name, ''), p_team_id),
                p_scopes, 'slack_workspace_token', p_at)
        ON CONFLICT (tenant_id, source_id, external_account_id) DO UPDATE
            SET display_name = COALESCE(NULLIF(EXCLUDED.display_name, ''),
                                        integration.display_name),
                scope        = EXCLUDED.scope,
                revoked_at   = NULL
        RETURNING id INTO v_integration;

        INSERT INTO slack_workspace_token (
            tenant_id, integration_id, team_id, team_name, bot_user_id, app_id,
            installer_slack_user_id, scopes, token_ciphertext, key_version,
            installed_at)
        VALUES (v_tenant, v_integration, p_team_id, p_team_name, p_bot_user_id,
                p_app_id, p_installer, p_scopes, p_ciphertext, p_key_version, p_at)
        ON CONFLICT (tenant_id, integration_id) DO UPDATE
            SET team_name        = EXCLUDED.team_name,
                bot_user_id      = EXCLUDED.bot_user_id,
                app_id           = EXCLUDED.app_id,
                installer_slack_user_id = EXCLUDED.installer_slack_user_id,
                scopes           = EXCLUDED.scopes,
                token_ciphertext = EXCLUDED.token_ciphertext,
                key_version      = EXCLUDED.key_version,
                rotated_at       = p_at,
                revoked_at       = NULL,
                revoked_reason   = NULL
        RETURNING id INTO v_token;

        UPDATE install_claim SET redeemed_at = p_at WHERE token_hash = p_token_hash;

        RETURN QUERY SELECT 'ok'::text, v_tenant, v_integration, v_token;
    END;
    $fn$;
REVOKE ALL ON FUNCTION argus_claim_slack_workspace(
    text, text, text, text, text, text, text, text, integer, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION argus_claim_slack_workspace(
    text, text, text, text, text, text, text, text, integer, text) TO argus_app;


-- --- 6e. 7.2's GitHub claim redeemer learns about providers -----------------
-- Same signature, so CREATE OR REPLACE is enough. The only change is the
-- `provider = 'github'` line: without it, a Slack install link handed to a
-- pilot contact would also work as a GitHub install link.
CREATE OR REPLACE FUNCTION argus_claim_installation(
        p_token_hash text, p_installation_id text, p_account_login text,
        p_account_type text, p_scope text, p_at text)
    RETURNS TABLE (out_tenant_id uuid, out_integration_id bigint)
    LANGUAGE plpgsql SECURITY DEFINER
    AS $fn$
    DECLARE v_tenant uuid; v_source bigint; v_integration bigint;
    BEGIN
        SELECT c.tenant_id INTO v_tenant FROM install_claim c
            WHERE c.token_hash = p_token_hash
              AND c.provider = 'github'
              AND c.redeemed_at IS NULL
              AND c.expires_at > p_at;
        IF v_tenant IS NULL THEN
            RETURN;
        END IF;

        SELECT s.id INTO v_source FROM source s
            WHERE s.tenant_id = v_tenant AND s.name = 'github';

        INSERT INTO integration (tenant_id, source_id, external_account_id,
                                  display_name, scope, credential_ref, installed_at)
        VALUES (v_tenant, v_source, p_installation_id, p_account_login,
                p_scope, 'github_app_installation', p_at)
        ON CONFLICT (tenant_id, source_id, external_account_id) DO UPDATE
            SET display_name = EXCLUDED.display_name,
                scope        = EXCLUDED.scope,
                revoked_at   = NULL
        RETURNING id INTO v_integration;

        UPDATE install_claim SET redeemed_at = p_at WHERE token_hash = p_token_hash;

        INSERT INTO pending_installation (installation_id, account_login, account_type,
                                           status, claimed_tenant_id, first_seen_at,
                                           last_seen_at, last_event_type, last_event_action)
        VALUES (p_installation_id, COALESCE(NULLIF(p_account_login, ''), '(pending)'),
                COALESCE(NULLIF(p_account_type, ''), 'unknown'), 'claimed',
                v_tenant, p_at, p_at, 'setup_redirect', 'claimed')
        ON CONFLICT (installation_id) DO UPDATE
            SET status = 'claimed', claimed_tenant_id = v_tenant, last_seen_at = p_at,
                last_event_type = 'setup_redirect', last_event_action = 'claimed';

        RETURN QUERY SELECT v_tenant, v_integration;
    END;
    $fn$;
REVOKE ALL ON FUNCTION argus_claim_installation(text, text, text, text, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION argus_claim_installation(text, text, text, text, text, text)
    TO argus_app;


-- ===========================================================================
-- 7. The same verification schema_pg.sql ends with, re-run here.
--
-- It is cheap, it runs on every boot, and it is the only thing standing
-- between "we added a table in a later phase" and "we added an unprotected
-- table in a later phase."
-- ===========================================================================
DO $verify$
DECLARE missing text;
BEGIN
    SELECT string_agg(c.relname, ', ') INTO missing
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relkind = 'r'
      AND c.relname NOT IN ('tenant_api_key', 'audit_log', 'pending_installation')
      AND NOT (c.relrowsecurity AND c.relforcerowsecurity);
    IF missing IS NOT NULL THEN
        RAISE EXCEPTION 'RLS not forced on: %', missing;
    END IF;
END
$verify$;
