-- ===========================================================================
-- ARGUS — Phase 7.1 multi-tenant Postgres schema
-- Ported from src/schema.sql (SQLite, Phase 2.1 + Phase 6.1/6.3) — D-124..D-128
--
-- Isolation model (D-125): ONE Postgres database, ONE schema, a `tenant_id`
-- column on every data table, and Postgres Row-Level Security FORCED on every
-- one of them. The API process connects as `argus_app`, a role with no
-- BYPASSRLS and no ownership of any table, and binds a tenant per request with
-- `SET LOCAL argus.tenant_id`. If that binding is missing the policies evaluate
-- to NULL and the query returns zero rows: it fails closed, never open.
--
-- Cross-tenant foreign keys are made physically impossible (D-126): every data
-- table carries UNIQUE (id, tenant_id) and every foreign key is composite,
-- carrying tenant_id through. A row in tenant A cannot reference a row in
-- tenant B even if the application tries.
--
-- Type fidelity (D-127): 0/1 integer flags and ISO-8601 TEXT timestamps are
-- kept exactly as Phase 2 defined them rather than "corrected" to BOOLEAN and
-- TIMESTAMPTZ, so the frozen engine's own SQL (detectors.py, sprint_filter.py,
-- digest.py — ~250KB of working, proven Phase 6 code) keeps running unchanged
-- against this database. CHECK constraints preserve the self-documentation.
-- ===========================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------------------
-- 0. Control plane — tenants and their credentials.
--    These tables are deliberately NOT tenant-scoped: they are the thing that
--    resolves a request to a tenant in the first place. `argus_app` is granted
--    no direct read on tenant_api_key at all (see roles.sql); it can only call
--    the SECURITY DEFINER resolver below.
-- ---------------------------------------------------------------------------

CREATE TABLE tenant (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    slug            TEXT NOT NULL UNIQUE
                    CHECK (slug ~ '^[a-z0-9][a-z0-9-]{1,38}[a-z0-9]$'),
    display_name    TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'shadow'
                    CHECK (status IN ('shadow','live','suspended','offboarded')),
    -- Phase 7.6's 2-week Shadow Mode is a tenant state, not a config flag
    -- buried in code: 'shadow' means detect and store but never DM a human.
    shadow_until    TEXT,
    created_at      TEXT NOT NULL,
    offboarded_at   TEXT
);

CREATE TABLE tenant_api_key (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    -- The plaintext key is shown exactly once, at creation, and never stored.
    key_prefix      TEXT NOT NULL UNIQUE,
    key_hash        TEXT NOT NULL,
    label           TEXT,
    created_at      TEXT NOT NULL,
    last_used_at    TEXT,
    revoked_at      TEXT
);
CREATE INDEX ix_apikey_tenant ON tenant_api_key(tenant_id);

-- Every tenant-bound request is recorded, including the ones that were
-- refused. Phase 9's SOC 2 conversation starts from this table existing.
CREATE TABLE audit_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID REFERENCES tenant(id) ON DELETE SET NULL,
    at              TEXT NOT NULL,
    actor           TEXT NOT NULL,          -- 'tenant:<slug>' | 'admin' | 'anonymous'
    action          TEXT NOT NULL,
    detail          TEXT,
    outcome         TEXT NOT NULL CHECK (outcome IN ('ok','denied','error'))
);
CREATE INDEX ix_audit_tenant ON audit_log(tenant_id, at);

-- ---------------------------------------------------------------------------
-- The tenant binding. current_setting(..., true) returns NULL when unset,
-- so every RLS policy below evaluates to NULL -> no rows. Fail closed.
-- ---------------------------------------------------------------------------
CREATE FUNCTION argus_current_tenant() RETURNS uuid
    LANGUAGE sql STABLE
    AS $fn$ SELECT nullif(current_setting('argus.tenant_id', true), '')::uuid $fn$;

-- The only way `argus_app` can turn a presented key into a tenant.
-- SECURITY DEFINER so the app role never needs SELECT on tenant_api_key.
CREATE FUNCTION argus_resolve_api_key(p_prefix text, p_hash text)
    RETURNS TABLE (tenant_id uuid, key_id uuid, slug text, status text, shadow_until text)
    LANGUAGE sql SECURITY DEFINER STABLE
    AS $fn$
        SELECT t.id, k.id, t.slug, t.status, t.shadow_until
        FROM tenant_api_key k
        JOIN tenant t ON t.id = k.tenant_id
        WHERE k.key_prefix = p_prefix
          AND k.revoked_at IS NULL
          AND t.status <> 'offboarded'
          -- constant-time-ish compare; the token is 256 bits of entropy so a
          -- timing side channel here is not the realistic attack anyway
          AND k.key_hash = p_hash
    $fn$;

-- ===========================================================================
-- Sections 1-10 — Phase 2's frozen GitHub model, ported verbatim in meaning.
-- Every table gains exactly two things: a tenant_id, and composite foreign
-- keys that carry it. No column was renamed, retyped, dropped or widened.
-- ===========================================================================

-- 1. Provenance ------------------------------------------------------------

CREATE TABLE source (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    name            TEXT NOT NULL,
    base_url        TEXT NOT NULL,
    UNIQUE (id, tenant_id),
    UNIQUE (tenant_id, name)
);

CREATE TABLE snapshot (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    source_id       BIGINT NOT NULL,
    project_id      BIGINT NOT NULL,
    observed_at     TEXT NOT NULL,
    started_at      TEXT NOT NULL,
    completed_at    TEXT,
    is_complete     INTEGER NOT NULL DEFAULT 0 CHECK (is_complete IN (0,1)),
    tool_version    TEXT,
    notes           TEXT,
    UNIQUE (id, tenant_id),
    FOREIGN KEY (source_id, tenant_id) REFERENCES source(id, tenant_id)
);

CREATE TABLE "fetch" (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    snapshot_id     BIGINT NOT NULL,
    url             TEXT NOT NULL,
    purpose         TEXT NOT NULL,
    attempt         INTEGER NOT NULL,
    tool            TEXT NOT NULL,
    requested_at    TEXT NOT NULL,
    duration_ms     INTEGER,
    outcome         TEXT NOT NULL CHECK (outcome IN ('ok','failed','corrupt','empty')),
    http_status     INTEGER,
    error_detail    TEXT,
    UNIQUE (id, tenant_id),
    FOREIGN KEY (snapshot_id, tenant_id) REFERENCES snapshot(id, tenant_id)
);
CREATE INDEX ix_fetch_snapshot ON "fetch"(tenant_id, snapshot_id);
CREATE INDEX ix_fetch_url      ON "fetch"(tenant_id, snapshot_id, url);
CREATE INDEX ix_fetch_outcome  ON "fetch"(tenant_id, snapshot_id, outcome);

-- 2. Core entities ---------------------------------------------------------

CREATE TABLE project (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    source_id       BIGINT NOT NULL,
    source_key      TEXT NOT NULL,
    display_name    TEXT NOT NULL,
    uses_work_items INTEGER NOT NULL DEFAULT 1 CHECK (uses_work_items IN (0,1)),
    UNIQUE (id, tenant_id),
    UNIQUE (tenant_id, source_id, source_key),
    FOREIGN KEY (source_id, tenant_id) REFERENCES source(id, tenant_id)
);

CREATE TABLE actor (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    source_id       BIGINT NOT NULL,
    source_key      TEXT NOT NULL,
    display_name    TEXT,
    kind            TEXT NOT NULL CHECK (kind IN ('human','bot','unknown')),
    kind_reason     TEXT NOT NULL CHECK (kind_reason IN
                        ('suffix_bot','known_bot_list','profile_flag',
                         'assumed_human','unresolved')),
    person_id       BIGINT,
    UNIQUE (id, tenant_id),
    UNIQUE (tenant_id, source_id, source_key),
    FOREIGN KEY (source_id, tenant_id) REFERENCES source(id, tenant_id)
);

CREATE TABLE work_item (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    snapshot_id         BIGINT NOT NULL,
    project_id          BIGINT NOT NULL,
    source_number       INTEGER NOT NULL,
    kind                TEXT NOT NULL CHECK (kind IN ('issue','change_request')),
    title               TEXT NOT NULL,
    body                TEXT,
    state               TEXT NOT NULL CHECK (state IN ('open','closed','merged')),
    is_draft            INTEGER NOT NULL DEFAULT 0 CHECK (is_draft IN (0,1)),
    author_id           BIGINT,
    created_at          TEXT NOT NULL,
    closed_at           TEXT,
    milestone_id        BIGINT,
    url                 TEXT NOT NULL,
    source_updated_at   TEXT,
    fetch_id            BIGINT,
    source_payload      TEXT,
    UNIQUE (id, tenant_id),
    UNIQUE (tenant_id, snapshot_id, project_id, source_number),
    FOREIGN KEY (snapshot_id, tenant_id) REFERENCES snapshot(id, tenant_id),
    FOREIGN KEY (project_id, tenant_id)  REFERENCES project(id, tenant_id),
    FOREIGN KEY (author_id, tenant_id)   REFERENCES actor(id, tenant_id),
    FOREIGN KEY (fetch_id, tenant_id)    REFERENCES "fetch"(id, tenant_id)
);
CREATE INDEX ix_item_project ON work_item(tenant_id, snapshot_id, project_id, state);
CREATE INDEX ix_item_created ON work_item(tenant_id, snapshot_id, project_id, created_at);

-- 3. The event log ---------------------------------------------------------

CREATE TABLE event (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    snapshot_id         BIGINT NOT NULL,
    work_item_id        BIGINT NOT NULL,
    type                TEXT NOT NULL CHECK (type IN (
                            'opened','closed','reopened','commented',
                            'review_submitted','review_requested','review_request_removed',
                            'assigned','unassigned','labeled','unlabeled',
                            'milestoned','demilestoned','committed','force_pushed',
                            'ready_for_review','converted_to_draft','renamed',
                            'referenced','cross_referenced','reacted','other')),
    actor_id            BIGINT,
    subject_actor_id    BIGINT,
    occurred_at         TEXT,
    date_precision      TEXT NOT NULL DEFAULT 'exact'
                        CHECK (date_precision IN ('exact','at_or_before','unknown')),
    counts_as_human     INTEGER NOT NULL DEFAULT 0 CHECK (counts_as_human IN (0,1)),
    human_reason        TEXT NOT NULL CHECK (human_reason IN (
                            'human','bot_account','ai_drafted_footnote',
                            'automation_event','unknown_actor')),
    detail              TEXT,
    fetch_id            BIGINT,
    UNIQUE (id, tenant_id),
    FOREIGN KEY (snapshot_id, tenant_id)      REFERENCES snapshot(id, tenant_id),
    FOREIGN KEY (work_item_id, tenant_id)     REFERENCES work_item(id, tenant_id),
    FOREIGN KEY (actor_id, tenant_id)         REFERENCES actor(id, tenant_id),
    FOREIGN KEY (subject_actor_id, tenant_id) REFERENCES actor(id, tenant_id),
    FOREIGN KEY (fetch_id, tenant_id)         REFERENCES "fetch"(id, tenant_id)
);
CREATE INDEX ix_event_item       ON event(tenant_id, work_item_id, occurred_at);
CREATE INDEX ix_event_item_human ON event(tenant_id, work_item_id, counts_as_human, occurred_at);
CREATE INDEX ix_event_actor      ON event(tenant_id, work_item_id, actor_id, counts_as_human, occurred_at);
CREATE INDEX ix_event_type       ON event(tenant_id, work_item_id, type, occurred_at);

-- 4. Conversation ----------------------------------------------------------

CREATE TABLE comment (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    event_id            BIGINT NOT NULL,
    work_item_id        BIGINT NOT NULL,
    actor_id            BIGINT,
    created_at          TEXT,
    body                TEXT NOT NULL,
    authorship          TEXT NOT NULL CHECK (authorship IN
                            ('human','bot','ai_drafted_under_human_account')),
    has_question_mark   INTEGER NOT NULL DEFAULT 0 CHECK (has_question_mark IN (0,1)),
    UNIQUE (id, tenant_id),
    FOREIGN KEY (event_id, tenant_id)     REFERENCES event(id, tenant_id),
    FOREIGN KEY (work_item_id, tenant_id) REFERENCES work_item(id, tenant_id),
    FOREIGN KEY (actor_id, tenant_id)     REFERENCES actor(id, tenant_id)
);
CREATE INDEX ix_comment_item ON comment(tenant_id, work_item_id, created_at);

CREATE TABLE mention (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    comment_id          BIGINT NOT NULL,
    work_item_id        BIGINT NOT NULL,
    mentioned_actor_id  BIGINT,
    mentioned_team      TEXT,
    in_code_or_quote    INTEGER NOT NULL DEFAULT 0 CHECK (in_code_or_quote IN (0,1)),
    UNIQUE (id, tenant_id),
    CHECK (mentioned_actor_id IS NOT NULL OR mentioned_team IS NOT NULL),
    FOREIGN KEY (comment_id, tenant_id)         REFERENCES comment(id, tenant_id),
    FOREIGN KEY (work_item_id, tenant_id)       REFERENCES work_item(id, tenant_id),
    FOREIGN KEY (mentioned_actor_id, tenant_id) REFERENCES actor(id, tenant_id)
);
CREATE INDEX ix_mention_item ON mention(tenant_id, work_item_id);

-- 5. Review ----------------------------------------------------------------

CREATE TABLE review (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    event_id        BIGINT NOT NULL,
    work_item_id    BIGINT NOT NULL,
    actor_id        BIGINT,
    state           TEXT NOT NULL CHECK (state IN
                        ('approved','changes_requested','commented','dismissed')),
    submitted_at    TEXT,
    UNIQUE (id, tenant_id),
    FOREIGN KEY (event_id, tenant_id)     REFERENCES event(id, tenant_id),
    FOREIGN KEY (work_item_id, tenant_id) REFERENCES work_item(id, tenant_id),
    FOREIGN KEY (actor_id, tenant_id)     REFERENCES actor(id, tenant_id)
);
CREATE INDEX ix_review_item ON review(tenant_id, work_item_id, submitted_at);

CREATE TABLE review_request (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    work_item_id    BIGINT NOT NULL,
    actor_id        BIGINT,
    team            TEXT,
    requested_by    BIGINT,
    requested_at    TEXT,
    removed_at      TEXT,
    origin          TEXT NOT NULL DEFAULT 'manual'
                    CHECK (origin IN ('manual','codeowners','unknown')),
    UNIQUE (id, tenant_id),
    CHECK (actor_id IS NOT NULL OR team IS NOT NULL),
    FOREIGN KEY (work_item_id, tenant_id) REFERENCES work_item(id, tenant_id),
    FOREIGN KEY (actor_id, tenant_id)     REFERENCES actor(id, tenant_id),
    FOREIGN KEY (requested_by, tenant_id) REFERENCES actor(id, tenant_id)
);
CREATE INDEX ix_revreq_item ON review_request(tenant_id, work_item_id, requested_at);

-- 6. Ownership, labels, milestones ----------------------------------------

CREATE TABLE assignment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    work_item_id    BIGINT NOT NULL,
    actor_id        BIGINT NOT NULL,
    assigned_at     TEXT,
    unassigned_at   TEXT,
    assigned_by     BIGINT,
    is_automatic    INTEGER NOT NULL DEFAULT 0 CHECK (is_automatic IN (0,1)),
    UNIQUE (id, tenant_id),
    FOREIGN KEY (work_item_id, tenant_id) REFERENCES work_item(id, tenant_id),
    FOREIGN KEY (actor_id, tenant_id)     REFERENCES actor(id, tenant_id),
    FOREIGN KEY (assigned_by, tenant_id)  REFERENCES actor(id, tenant_id)
);
CREATE INDEX ix_assign_item ON assignment(tenant_id, work_item_id, assigned_at);

CREATE TABLE label (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id               UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    project_id              BIGINT NOT NULL,
    name                    TEXT NOT NULL,
    description             TEXT,
    classification          TEXT NOT NULL DEFAULT 'unclassified'
                            CHECK (classification IN
                                ('blocker','healthy_slowness','triage_only',
                                 'neither','unclassified')),
    classification_status   TEXT NOT NULL DEFAULT 'proposed'
                            CHECK (classification_status IN ('proposed','confirmed')),
    classified_at           TEXT,
    UNIQUE (id, tenant_id),
    UNIQUE (tenant_id, project_id, name),
    FOREIGN KEY (project_id, tenant_id) REFERENCES project(id, tenant_id)
);

CREATE TABLE work_item_label (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    work_item_id    BIGINT NOT NULL,
    label_id        BIGINT NOT NULL,
    applied_at      TEXT,
    applied_by      BIGINT,
    removed_at      TEXT,
    UNIQUE (id, tenant_id),
    FOREIGN KEY (work_item_id, tenant_id) REFERENCES work_item(id, tenant_id),
    FOREIGN KEY (label_id, tenant_id)     REFERENCES label(id, tenant_id),
    FOREIGN KEY (applied_by, tenant_id)   REFERENCES actor(id, tenant_id)
);
CREATE INDEX ix_wil_item  ON work_item_label(tenant_id, work_item_id);
CREATE INDEX ix_wil_label ON work_item_label(tenant_id, label_id);

CREATE TABLE milestone (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    project_id      BIGINT NOT NULL,
    title           TEXT NOT NULL,
    state           TEXT NOT NULL CHECK (state IN ('open','closed')),
    due_on          TEXT,
    closed_at       TEXT,
    UNIQUE (id, tenant_id),
    UNIQUE (tenant_id, project_id, title),
    FOREIGN KEY (project_id, tenant_id) REFERENCES project(id, tenant_id)
);

-- 7. Relationships ---------------------------------------------------------

CREATE TABLE reference (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    from_work_item_id   BIGINT NOT NULL,
    to_project_key      TEXT NOT NULL,
    to_work_item_id     BIGINT,
    to_number           INTEGER,
    relation            TEXT NOT NULL CHECK (relation IN
                            ('blocks','blocked_by','closes','closed_by',
                             'linked_pr','mentions','duplicate_of','unknown')),
    is_cross_project    INTEGER NOT NULL DEFAULT 0 CHECK (is_cross_project IN (0,1)),
    detected_at         TEXT,
    UNIQUE (id, tenant_id),
    FOREIGN KEY (from_work_item_id, tenant_id) REFERENCES work_item(id, tenant_id),
    FOREIGN KEY (to_work_item_id, tenant_id)   REFERENCES work_item(id, tenant_id)
);
CREATE INDEX ix_ref_from ON reference(tenant_id, from_work_item_id, relation);
CREATE INDEX ix_ref_to   ON reference(tenant_id, to_work_item_id);

-- 8. Mechanical readiness --------------------------------------------------

CREATE TABLE readiness (
    work_item_id    BIGINT PRIMARY KEY,
    tenant_id       UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    merge_state     TEXT NOT NULL DEFAULT 'unknown'
                    CHECK (merge_state IN ('clean','blocked','unknown')),
    checks_state    TEXT NOT NULL DEFAULT 'unknown'
                    CHECK (checks_state IN ('clean','blocked','unknown')),
    cla_state       TEXT NOT NULL DEFAULT 'unknown'
                    CHECK (cla_state IN ('clean','blocked','unknown')),
    evidence_note   TEXT,
    UNIQUE (work_item_id, tenant_id),
    FOREIGN KEY (work_item_id, tenant_id) REFERENCES work_item(id, tenant_id)
);

-- 9. What we could not see -------------------------------------------------

CREATE TABLE evidence_gap (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    snapshot_id     BIGINT NOT NULL,
    work_item_id    BIGINT,
    gap_type        TEXT NOT NULL CHECK (gap_type IN (
                        'timeline_not_rendered','timeline_truncated','event_without_date',
                        'fetch_failed','content_corrupt','actor_unresolved')),
    detail          TEXT,
    detected_at     TEXT NOT NULL,
    UNIQUE (id, tenant_id),
    FOREIGN KEY (snapshot_id, tenant_id)  REFERENCES snapshot(id, tenant_id),
    FOREIGN KEY (work_item_id, tenant_id) REFERENCES work_item(id, tenant_id)
);
CREATE INDEX ix_gap_item ON evidence_gap(tenant_id, work_item_id);
CREATE INDEX ix_gap_snap ON evidence_gap(tenant_id, snapshot_id, gap_type);

-- 11. Jira / Linear --------------------------------------------------------

CREATE TABLE sprint (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    project_id      BIGINT NOT NULL,
    source_key      TEXT NOT NULL,
    name            TEXT NOT NULL,
    state           TEXT NOT NULL DEFAULT 'unknown'
                    CHECK (state IN ('future','active','closed','unknown')),
    starts_at       TEXT,
    ends_at         TEXT,
    UNIQUE (id, tenant_id),
    UNIQUE (tenant_id, project_id, source_key),
    FOREIGN KEY (project_id, tenant_id) REFERENCES project(id, tenant_id)
);

CREATE TABLE ticket (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    source_id           BIGINT NOT NULL,
    project_id          BIGINT NOT NULL,
    source_key          TEXT NOT NULL,
    title               TEXT NOT NULL,
    ticket_type         TEXT NOT NULL DEFAULT 'unknown'
                        CHECK (ticket_type IN ('story','bug','task','epic','subtask','unknown')),
    source_status       TEXT NOT NULL,
    status_category     TEXT NOT NULL DEFAULT 'unknown'
                        CHECK (status_category IN
                            ('backlog','ready','in_progress','in_review','done','canceled','unknown')),
    sprint_id           BIGINT,
    assignee_actor_id   BIGINT,
    created_at          TEXT NOT NULL,
    source_updated_at   TEXT,
    fetch_id            BIGINT,
    source_payload      TEXT,
    UNIQUE (id, tenant_id),
    UNIQUE (tenant_id, source_id, project_id, source_key),
    FOREIGN KEY (source_id, tenant_id)         REFERENCES source(id, tenant_id),
    FOREIGN KEY (project_id, tenant_id)        REFERENCES project(id, tenant_id),
    FOREIGN KEY (sprint_id, tenant_id)         REFERENCES sprint(id, tenant_id),
    FOREIGN KEY (assignee_actor_id, tenant_id) REFERENCES actor(id, tenant_id),
    FOREIGN KEY (fetch_id, tenant_id)          REFERENCES "fetch"(id, tenant_id)
);
CREATE INDEX ix_ticket_project ON ticket(tenant_id, project_id, status_category);
CREATE INDEX ix_ticket_sprint  ON ticket(tenant_id, sprint_id);

CREATE TABLE ticket_status_event (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    ticket_id           BIGINT NOT NULL,
    from_status         TEXT,
    to_status           TEXT NOT NULL,
    to_status_category  TEXT NOT NULL
                        CHECK (to_status_category IN
                            ('backlog','ready','in_progress','in_review','done','canceled','unknown')),
    changed_at          TEXT,
    fetch_id            BIGINT,
    UNIQUE (id, tenant_id),
    FOREIGN KEY (ticket_id, tenant_id) REFERENCES ticket(id, tenant_id),
    FOREIGN KEY (fetch_id, tenant_id)  REFERENCES "fetch"(id, tenant_id)
);
CREATE INDEX ix_tse_ticket ON ticket_status_event(tenant_id, ticket_id, changed_at);

CREATE TABLE ticket_link (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    ticket_id           BIGINT NOT NULL,
    work_item_id        BIGINT NOT NULL,
    link_method         TEXT NOT NULL CHECK (link_method IN
                            ('smart_commit','branch_name','pr_title_key','api_link','manual')),
    confidence          TEXT NOT NULL DEFAULT 'high'
                        CHECK (confidence IN ('high','medium','low')),
    detected_at         TEXT NOT NULL,
    UNIQUE (id, tenant_id),
    UNIQUE (tenant_id, ticket_id, work_item_id),
    FOREIGN KEY (ticket_id, tenant_id)    REFERENCES ticket(id, tenant_id),
    FOREIGN KEY (work_item_id, tenant_id) REFERENCES work_item(id, tenant_id)
);
CREATE INDEX ix_tlink_item   ON ticket_link(tenant_id, work_item_id);
CREATE INDEX ix_tlink_ticket ON ticket_link(tenant_id, ticket_id);

-- 12. Slack: install, presence, triage ------------------------------------

CREATE TABLE integration (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id               UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    source_id               BIGINT NOT NULL,
    project_id              BIGINT,
    external_account_id     TEXT NOT NULL,
    display_name            TEXT,
    scope                   TEXT,
    credential_ref          TEXT NOT NULL,
    installed_at            TEXT NOT NULL,
    revoked_at              TEXT,
    UNIQUE (id, tenant_id),
    UNIQUE (tenant_id, source_id, external_account_id),
    FOREIGN KEY (source_id, tenant_id)  REFERENCES source(id, tenant_id),
    FOREIGN KEY (project_id, tenant_id) REFERENCES project(id, tenant_id)
);

CREATE TABLE slack_identity (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    integration_id  BIGINT NOT NULL,
    actor_id        BIGINT NOT NULL,
    slack_user_id   TEXT,
    matched_email   TEXT,
    resolved_via    TEXT NOT NULL CHECK (resolved_via IN ('manual_map','email_lookup','unresolved')),
    resolved_at     TEXT NOT NULL,
    UNIQUE (id, tenant_id),
    UNIQUE (tenant_id, integration_id, actor_id),
    CHECK (slack_user_id IS NOT NULL OR resolved_via = 'unresolved'),
    FOREIGN KEY (integration_id, tenant_id) REFERENCES integration(id, tenant_id),
    FOREIGN KEY (actor_id, tenant_id)       REFERENCES actor(id, tenant_id)
);
CREATE INDEX ix_slackid_actor ON slack_identity(tenant_id, actor_id);

CREATE TABLE presence (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    actor_id        BIGINT NOT NULL,
    status          TEXT NOT NULL CHECK (status IN ('available','out_of_office','unknown')),
    detected_via    TEXT NOT NULL DEFAULT 'unknown'
                    CHECK (detected_via IN ('slack_status','calendar_sync','manual','unknown')),
    effective_from  TEXT NOT NULL,
    effective_to    TEXT,
    detected_at     TEXT NOT NULL,
    UNIQUE (id, tenant_id),
    FOREIGN KEY (actor_id, tenant_id) REFERENCES actor(id, tenant_id)
);
CREATE INDEX ix_presence_actor ON presence(tenant_id, actor_id, effective_from);

CREATE TABLE triage_message (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id               UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    integration_id          BIGINT NOT NULL,
    work_item_id            BIGINT,
    ticket_id               BIGINT,
    sent_to_actor_id        BIGINT NOT NULL,
    external_channel_id     TEXT,
    external_message_ts     TEXT,
    sent_at                 TEXT NOT NULL,
    snooze_until            TEXT,
    status                  TEXT NOT NULL DEFAULT 'sent'
                            CHECK (status IN
                                ('sent','responded','expired','suppressed_presence','failed')),
    suppressed_reason       TEXT,
    UNIQUE (id, tenant_id),
    CHECK (work_item_id IS NOT NULL OR ticket_id IS NOT NULL),
    CHECK (status = 'suppressed_presence'
           OR (external_channel_id IS NOT NULL AND external_message_ts IS NOT NULL)),
    FOREIGN KEY (integration_id, tenant_id)   REFERENCES integration(id, tenant_id),
    FOREIGN KEY (work_item_id, tenant_id)     REFERENCES work_item(id, tenant_id),
    FOREIGN KEY (ticket_id, tenant_id)        REFERENCES ticket(id, tenant_id),
    FOREIGN KEY (sent_to_actor_id, tenant_id) REFERENCES actor(id, tenant_id)
);
CREATE INDEX ix_triagemsg_item   ON triage_message(tenant_id, work_item_id);
CREATE INDEX ix_triagemsg_ticket ON triage_message(tenant_id, ticket_id);
CREATE INDEX ix_triagemsg_actor  ON triage_message(tenant_id, sent_to_actor_id, status);

CREATE TABLE triage_response (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    triage_message_id   BIGINT NOT NULL,
    response_type       TEXT NOT NULL
                        CHECK (response_type IN ('handled_offline','blocked_on','snooze_7d')),
    blocked_on_text     TEXT,
    responded_at        TEXT NOT NULL,
    raw_payload         TEXT,
    UNIQUE (id, tenant_id),
    FOREIGN KEY (triage_message_id, tenant_id) REFERENCES triage_message(id, tenant_id)
);
CREATE INDEX ix_triageresp_msg ON triage_response(tenant_id, triage_message_id);

-- ===========================================================================
-- 13. Phase 7 — the pilot record. New at 7.1, D-128.
--
-- Phase 6 computed FIRE/SUPPRESSED/ABSTAIN in memory and wrote a JSON file.
-- That was fine for one team run by hand; it cannot answer Phase 7's own
-- questions ("alert satisfaction across 15 teams", "did the multi-source
-- pipeline beat Part I's 65.5% ceiling"), because nothing durable records
-- what was decided or what the human said back. These four tables are that
-- record. They are the reason Phase 7 can rule on the criterion Phase 6
-- deferred (D-123).
-- ===========================================================================

CREATE TABLE ingest_run (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    snapshot_id     BIGINT,
    trigger_kind    TEXT NOT NULL CHECK (trigger_kind IN ('scheduled','manual','webhook','backfill')),
    status          TEXT NOT NULL DEFAULT 'queued'
                    CHECK (status IN ('queued','running','succeeded','failed','cancelled')),
    started_at      TEXT NOT NULL,
    finished_at     TEXT,
    -- What the run actually did, so a failed pilot night is diagnosable
    -- without reading logs: counts, and the first error if there was one.
    items_checked   INTEGER NOT NULL DEFAULT 0,
    alerts_fired    INTEGER NOT NULL DEFAULT 0,
    alerts_suppressed INTEGER NOT NULL DEFAULT 0,
    error_detail    TEXT,
    UNIQUE (id, tenant_id),
    FOREIGN KEY (snapshot_id, tenant_id) REFERENCES snapshot(id, tenant_id)
);
CREATE INDEX ix_ingestrun_tenant ON ingest_run(tenant_id, started_at DESC);

-- One row per sprint_filter decision. SUPPRESSED and ABSTAIN rows are stored
-- as deliberately as FIRE rows: the suppression count IS the measurement
-- Phase 6's kill criterion was about, and throwing it away would leave the
-- pilot unable to show its own work.
CREATE TABLE alert (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    ingest_run_id   BIGINT NOT NULL,
    work_item_id    BIGINT,
    ticket_id       BIGINT,
    -- Nullable and un-enumerated, for the same reason `reason` is: sprint_filter
    -- owns this vocabulary. It already emits values the first draft of this
    -- CHECK rejected ('P2-shaped', and NULL when both patterns abstain), which
    -- would have made the pilot record silently unable to store real output.
    pattern         TEXT,
    outcome         TEXT NOT NULL CHECK (outcome IN ('FIRE','SUPPRESSED','ABSTAIN')),
    -- sprint_filter's own reason string, stored verbatim. Not an enum here on
    -- purpose: the filter owns that vocabulary and a new reason must not
    -- require a database migration to be recordable.
    reason          TEXT NOT NULL,
    subject_actor_id BIGINT,
    decided_at      TEXT NOT NULL,
    UNIQUE (id, tenant_id),
    CHECK (work_item_id IS NOT NULL OR ticket_id IS NOT NULL),
    FOREIGN KEY (ingest_run_id, tenant_id)    REFERENCES ingest_run(id, tenant_id),
    FOREIGN KEY (work_item_id, tenant_id)     REFERENCES work_item(id, tenant_id),
    FOREIGN KEY (ticket_id, tenant_id)        REFERENCES ticket(id, tenant_id),
    FOREIGN KEY (subject_actor_id, tenant_id) REFERENCES actor(id, tenant_id)
);
CREATE INDEX ix_alert_run     ON alert(tenant_id, ingest_run_id, outcome);
CREATE INDEX ix_alert_outcome ON alert(tenant_id, outcome, decided_at);

CREATE TABLE digest_delivery (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    ingest_run_id   BIGINT NOT NULL,
    channel         TEXT NOT NULL CHECK (channel IN ('slack_dm','dashboard','none')),
    -- 'shadow' records a digest that was rendered and stored but deliberately
    -- not delivered, which is exactly what Phase 7.6's Shadow Mode is.
    status          TEXT NOT NULL CHECK (status IN ('delivered','shadow','failed')),
    rendered_text   TEXT NOT NULL,
    delivered_at    TEXT NOT NULL,
    failure_detail  TEXT,
    UNIQUE (id, tenant_id),
    FOREIGN KEY (ingest_run_id, tenant_id) REFERENCES ingest_run(id, tenant_id)
);
CREATE INDEX ix_digest_run ON digest_delivery(tenant_id, ingest_run_id);

-- Step 7.7 collects "a satisfaction response on every flagged item". This is
-- where it lands. Separate from triage_response because they answer different
-- questions: triage_response is what the developer DID about the work,
-- alert_feedback is whether the alert should have existed at all.
CREATE TABLE alert_feedback (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    alert_id        BIGINT NOT NULL,
    verdict         TEXT NOT NULL CHECK (verdict IN ('useful','not_useful','unsure')),
    note            TEXT,
    given_by_actor_id BIGINT,
    given_at        TEXT NOT NULL,
    UNIQUE (id, tenant_id),
    UNIQUE (tenant_id, alert_id),
    FOREIGN KEY (alert_id, tenant_id)          REFERENCES alert(id, tenant_id),
    FOREIGN KEY (given_by_actor_id, tenant_id) REFERENCES actor(id, tenant_id)
);
CREATE INDEX ix_feedback_alert ON alert_feedback(tenant_id, alert_id);

-- ===========================================================================
-- 14. Phase 7.2 — GitHub App installation lifecycle. New at 7.2, D-133+.
--
-- The GitHub App itself (its id, private key, webhook secret) is ONE set of
-- credentials for the whole deployment, not per-tenant data, so it lives in
-- environment variables on the host (same discipline as ARGUS_ADMIN_SECRET),
-- never in this database. What Postgres tracks is which *installation* (a
-- GitHub org/user choosing to install that one App) belongs to which tenant.
--
-- `install_claim` is how that binding happens without ever trusting a caller
-- to name their own tenant: an admin action mints a one-time token FOR a
-- specific tenant; GitHub's install flow hands that token back on its setup
-- redirect; only then does an `integration` row get created (via the
-- SECURITY DEFINER `argus_claim_installation`, roles.sql). A webhook that
-- arrives for an installation nobody has claimed yet is recorded in
-- `pending_installation` (control-plane, not tenant data — there is no
-- tenant to scope it to yet) and otherwise ignored until it is.
-- ===========================================================================

CREATE TABLE install_claim (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    token_hash      TEXT NOT NULL UNIQUE,
    created_at      TEXT NOT NULL,
    expires_at      TEXT NOT NULL,
    redeemed_at     TEXT,
    UNIQUE (id, tenant_id)
);
CREATE INDEX ix_installclaim_tenant ON install_claim(tenant_id);

-- Control-plane, deliberately NOT tenant-scoped (excluded from the RLS loop
-- below, same as tenant_api_key/audit_log) — its whole purpose is to hold
-- installation events for accounts that have no tenant yet, so there is no
-- tenant_id to bind them to.
CREATE TABLE pending_installation (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    installation_id     TEXT NOT NULL UNIQUE,
    account_login       TEXT NOT NULL,
    account_type        TEXT NOT NULL,
    status              TEXT NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending','claimed','suspended','deleted')),
    claimed_tenant_id   UUID REFERENCES tenant(id) ON DELETE SET NULL,
    first_seen_at       TEXT NOT NULL,
    last_seen_at        TEXT NOT NULL,
    last_event_type     TEXT,
    last_event_action   TEXT
);

-- Idempotency for GitHub's at-least-once delivery: `X-GitHub-Delivery` is a
-- UUID GitHub generates once per attempt-set and resends unchanged on retry.
-- Only meaningful once an installation is resolved to a tenant; the
-- unresolved case is deduplicated inside `pending_installation` itself
-- (upsert on installation_id).
CREATE TABLE webhook_delivery (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    installation_id TEXT NOT NULL,
    delivery_id     TEXT NOT NULL,
    event_type      TEXT NOT NULL,
    action          TEXT,
    received_at     TEXT NOT NULL,
    ingest_run_id   BIGINT,
    UNIQUE (id, tenant_id),
    UNIQUE (tenant_id, delivery_id),
    FOREIGN KEY (ingest_run_id, tenant_id) REFERENCES ingest_run(id, tenant_id)
);
CREATE INDEX ix_webhookdelivery_installation ON webhook_delivery(tenant_id, installation_id);

-- ===========================================================================
-- 10. The clocks — views, ported.
--
-- security_invoker = true is load-bearing, not tidiness (D-129). A Postgres
-- view without it checks the underlying tables' RLS against the VIEW OWNER,
-- not the caller — which would have made these three views a hole straight
-- through the isolation model. The isolation test suite has a case for
-- exactly this.
--
-- julianday() does not exist in Postgres. TRUNC (not FLOOR) reproduces
-- SQLite's CAST-toward-zero behaviour, so Phase 3's numbers still reproduce.
-- ===========================================================================

CREATE VIEW v_item_clock WITH (security_invoker = true) AS
SELECT
    w.id                                        AS work_item_id,
    w.tenant_id                                 AS tenant_id,
    s.observed_at                               AS observed_at,
    MAX(e.occurred_at)                          AS last_human_at,
    TRUNC(EXTRACT(EPOCH FROM (s.observed_at::timestamptz
                              - MAX(e.occurred_at)::timestamptz)) / 86400)::int
                                                AS days_silent,
    MAX(CASE WHEN e.date_precision <> 'exact' THEN 1 ELSE 0 END)
                                                AS is_lower_bound,
    COUNT(e.id)                                 AS human_event_count
FROM work_item w
JOIN snapshot s ON s.id = w.snapshot_id AND s.tenant_id = w.tenant_id
LEFT JOIN event e
       ON e.work_item_id = w.id
      AND e.tenant_id = w.tenant_id
      AND e.counts_as_human = 1
      AND e.occurred_at IS NOT NULL
GROUP BY w.id, w.tenant_id, s.observed_at;

CREATE VIEW v_actor_item_clock WITH (security_invoker = true) AS
SELECT
    e.work_item_id                              AS work_item_id,
    e.tenant_id                                 AS tenant_id,
    e.actor_id                                  AS actor_id,
    s.observed_at                               AS observed_at,
    MAX(e.occurred_at)                          AS last_action_at,
    TRUNC(EXTRACT(EPOCH FROM (s.observed_at::timestamptz
                              - MAX(e.occurred_at)::timestamptz)) / 86400)::int
                                                AS days_silent,
    MAX(CASE WHEN e.date_precision <> 'exact' THEN 1 ELSE 0 END)
                                                AS is_lower_bound
FROM event e
JOIN work_item w ON w.id = e.work_item_id AND w.tenant_id = e.tenant_id
JOIN snapshot s  ON s.id = w.snapshot_id  AND s.tenant_id = w.tenant_id
WHERE e.counts_as_human = 1
  AND e.occurred_at IS NOT NULL
  AND e.actor_id IS NOT NULL
GROUP BY e.work_item_id, e.tenant_id, e.actor_id, s.observed_at;

CREATE VIEW v_item_confidence WITH (security_invoker = true) AS
SELECT
    w.id                                        AS work_item_id,
    w.tenant_id                                 AS tenant_id,
    COUNT(g.id)                                 AS gap_count,
    string_agg(DISTINCT g.gap_type, ',')        AS gap_types,
    CASE WHEN COUNT(g.id) = 0 THEN 'high' ELSE 'low' END AS confidence
FROM work_item w
LEFT JOIN evidence_gap g
       ON g.work_item_id = w.id AND g.tenant_id = w.tenant_id
GROUP BY w.id, w.tenant_id;

-- ===========================================================================
-- Row-Level Security. Applied by loop rather than by 32 copy-pasted blocks so
-- that a table added later cannot silently be left unprotected — the
-- verification query at the bottom fails loudly if one is.
-- ===========================================================================

DO $rls$
DECLARE t text;
BEGIN
    FOR t IN
        SELECT tablename FROM pg_tables
        WHERE schemaname = 'public'
          -- pending_installation joins this exclusion list at 7.2: it has no
          -- tenant_id column at all (there is no tenant yet for an
          -- installation nobody has claimed), so the generic policy below
          -- would fail to even compile against it.
          AND tablename NOT IN ('tenant','tenant_api_key','audit_log','pending_installation')
    LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
        EXECUTE format(
            'CREATE POLICY tenant_isolation ON %I
                 USING (tenant_id = argus_current_tenant())
                 WITH CHECK (tenant_id = argus_current_tenant())', t);
    END LOOP;
END
$rls$;

-- Fail the migration outright if any data table escaped the loop above.
-- `tenant` gets its own policy: its primary key IS the tenant id. Without
-- this, any authenticated request could list every pilot team by name --
-- which is exactly what the first draft of /v1/me did.
ALTER TABLE tenant ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_self ON tenant
    USING (id = argus_current_tenant())
    WITH CHECK (id = argus_current_tenant());

DO $verify$
DECLARE missing text;
BEGIN
    SELECT string_agg(c.relname, ', ') INTO missing
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relkind = 'r'
      AND c.relname NOT IN ('tenant_api_key','audit_log','pending_installation')
      AND NOT (c.relrowsecurity AND c.relforcerowsecurity);
    IF missing IS NOT NULL THEN
        RAISE EXCEPTION 'RLS not forced on: %', missing;
    END IF;
END
$verify$;
